export enum Screens {
  Tabs = "Tabs",
  Home = "Home",
  Discover = "Discover",
  Settings = "Settings",
  Browser = "Browser",
  AppStack = "AppStack",
  OnboardingStack = "OnboardingStack",
  ///Onboard
  OnboardingScreen = "OnboardingScreen",
  LoginSocialScreen = "LoginSocialScreen",
  LoginScreen = "LoginScreen",
  SignUpIntro = "SignUpIntro",
  SignUp = "SignUp",
  ConfirmEmail = "ConfirmEmail",
  ConfirmOTP = "ConfirmOTP ",
  CreatePassword = "CreatePassword",
  SignUpOutro = "SignUpOutro",
  ResetPassword = "ResetPassword",

  NotificationsScreen = "NotificationsScreen",
  SettingsScreen = "SettingsScreen",
  ProfileScreen = "ProfileScreen",
  SecurityScreen = "SecurityScreen",
  AuthenticatorScreen = "AuthenticatorScreen",
  AuthenticatorConfirmOTPScreen = "AuthenticatorConfirmOTPScreen",
  AuthenticatorConfirmPasscodeScreen = "AuthenticatorConfirmPasscodeScreen",
  AuthenticatorGenerationScreen = "AuthenticatorGenerationScreen",
  DepositScreen = "DepositScreen",
  DepositDetailScreen = "DepositDetailScreen",
  WithdrawScreen = "WithdrawScreen",
  WithdrawDetailScreen = "WithdrawDetailScreen",
  TransactionHistoryScreen = "TransactionHistoryScreen",
}

export type AppScreen = Screens;
