export const fontFamily = {
  urbanist: {
    regular: "Satoshi-Regular",
    medium: "Satoshi-Medium",
    bold: "Satoshi-Bold",
    black: "Satoshi-Black",
    light: "Satoshi-Light",
  },
};

export const textVariants = {
  H1: {
    fontFamily: fontFamily.urbanist.bold,
    fontSize: 48,
    lineHeight: 57.6,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.2,
    fontWeight: 700,
  },
  H2: {
    fontFamily: fontFamily.urbanist.bold,
    fontSize: 40,
    lineHeight: 48,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.2,
    fontWeight: 700,
  },
  H3: {
    fontFamily: fontFamily.urbanist.bold,
    fontSize: 32,
    lineHeight: 38.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.2,
    fontWeight: 700,
  },
  H4: {
    fontFamily: fontFamily.urbanist.bold,
    fontSize: 24,
    lineHeight: 28.8,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.2,
    fontWeight: 700,
  },
  H5: {
    fontFamily: fontFamily.urbanist.bold,
    fontSize: 20,
    lineHeight: 24,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.2,
    fontWeight: 700,
  },
  H6: {
    fontFamily: fontFamily.urbanist.bold,
    fontSize: 18,
    lineHeight: 21.6,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.2,
    fontWeight: 700,
  },
  XlargeBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 18,
    lineHeight: 25.2,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 700,
  },
  XlargeSemiBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 18,
    lineHeight: 25.2,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 600,
  },
  XlargeMedium: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 18,
    lineHeight: 25.2,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 500,
  },
  XlargeRegular: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 18,
    lineHeight: 25.2,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 400,
  },
  largeBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 16,
    lineHeight: 22.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 700,
  },
  largeSemiBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 16,
    lineHeight: 22.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 600,
  },
  largeMedium: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 16,
    lineHeight: 22.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 500,
  },
  largeRegular: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 16,
    lineHeight: 22.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 400,
  },
  mediumBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 14,
    lineHeight: 19.6,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 700,
  },
  mediumSemiBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 14,
    lineHeight: 19.6,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 600,
  },
  mediumMedium: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 14,
    lineHeight: 19.6,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 500,
  },
  mediumRegular: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 14,
    lineHeight: 19.6,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 400,
  },
  smallBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 12,
    lineHeight: 14.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 700,
  },
  smallSemiBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 12,
    lineHeight: 14.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 600,
  },
  smallMedium: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 12,
    lineHeight: 14.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 500,
  },
  smallRegular: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 12,
    lineHeight: 14.4,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 400,
  },
  XSmallBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 10,
    lineHeight: 12,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 700,
  },
  XSmallSemiBold: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 10,
    lineHeight: 12,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 600,
  },
  XSmallMedium: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 10,
    lineHeight: 12,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 500,
  },
  XSmallRegular: {
    fontFamily: fontFamily.urbanist.medium,
    fontSize: 10,
    lineHeight: 12,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.4,
    fontWeight: 400,
  },
  monospace: {
    fontFamily: fontFamily.urbanist.light,
    fontSize: 15,
    lineHeight: 20,
    color: "textPrimary",
    maxFontSizeMultiplier: 1.2,
  },
};
